{
 "title": "Global Overview Revised",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Global CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (job) (rate(windows_cpu_processor_utility_total[3m])/rate(windows_cpu_processor_rtc_total[3m]))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Alerts Firing:", "type": "alertlist", "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 } },
  {
   "title": "Average Disk Activity (Megabyte per second)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_writes_total{volume =~ \"C:|S:|F:\"}[5m])+rate(windows_logical_disk_reads_total{volume =~ \"C:|S:|F:\"}[5m])",
     "legendFormat": "{{job}} {{volume}}"
    }
   ]
  },
  {
   "title": "Network Usage by Server - No Veeam (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job) (rate(windows_net_bytes_sent_total[5m]) + rate(windows_net_bytes_received_total[5m]))*0.000008\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_free_bytes{volume =~ \"C:|F:\"})/(windows_logical_disk_size_bytes{volume =~ \"C:|F:\"})*100",
     "legendFormat": "{{job}} {{volume}}"
    }
   ]
  },
  {
   "title": "RAM Free (Gigabytes)",
   "type": "gauge",
   "description": "Amount of RAM available in Gigabytes",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes / 1000000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Watchtower Ingest Traffic by Task (Megabit per second)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "((rate(pve_network_receive_bytes[45s]))*8)/1000000"
    }
   ]
  },
  {
   "title": "Watchtower RAM Usage (Gigabytes)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes/1000000000"
    }
   ]
  },
  {
   "title": "DNS Requests Per Second",
   "type": "timeseries",
   "description": "The amount of DNS requests sent to ArcadiaDC or newpdc (primary and secondary DNS servers) on the Riverland Network",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 37 },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(windows_dns_queries_total[3m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Telemetry Active on Stack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/local-lvm\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Historical ELK Stack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/RAIDZ-Moses\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Other Telemetry Backups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/RAID0-Backup\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Total Telemetry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pve_disk_usage_bytes)/1000000000000"
    }
   ]
  },
  {
   "title": "Most Recent Connection Locations and Metrics",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 43 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "destination.geo.location:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Watchtower Stack CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "(pve_cpu_usage_ratio*100)" }
   ]
  },
  {
   "title": "DHCP Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 56 },
   "targets": [
    {
     "expr": "windows_service_state{job=~\"ArcadiaDC|newpdc\", name=\"dhcpserver\", state=\"running\"}"
    }
   ]
  },
  {
   "title": "DNS Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 60 },
   "targets": [
    {
     "expr": "windows_service_state{job=~\"ArcadiaDC|newpdc\", name=\"dns\", state=\"running\"}"
    }
   ]
  },
  {
   "title": "Top Blocked DNS Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "DNS Responses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_dns_responses_total[60m])"
    }
   ]
  },
  {
   "title": "Recent Suspicious DNS Queries",
   "type": "logs",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 64 },
   "targets": [
    {
     "metrics": [
      { "id": "3", "settings": { "limit": "250" }, "type": "logs" }
     ],
     "query": "(\"ET DNS\" OR \"ET INFO DNS Query for Suspicious\") AND destination.ip:192.168.0.6 AND NOT soc.fields.requestMethod:GET AND NOT event.action:\"Searching Elasticsearch\" AND data_stream.dataset:suricata AND NOT \"ET EXPLOIT MS-SQL SQL Injection closing string plus line comment\" AND NOT source.ip:192.168.0.6 AND NOT source.ip:192.168.0.9 AND NOT source.ip:192.168.0.10",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top DNS Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Pihole DNS Filter Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 73 },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 11, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "DNS Queries Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today" }
   ]
  },
  {
   "title": "DNS Queries Blocked Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today" }
   ]
  },
  {
   "title": "Percent Blocked Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "New Connections over Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 84 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "zeek",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Domains Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "DNS Queries Today over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 88 },
   "targets": [
    { "expr": "pihole_ads_blocked_today" },
    { "expr": "pihole_queries_forwarded" },
    { "expr": "pihole_queries_cached" }
   ]
  },
  {
   "title": "Active Pihole Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 98 },
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  },
  {
   "title": "Recent RDP Connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 98 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:rdp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent FTP Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:ftp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Theme Changer",
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 118 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}