{
 "title": "WISE ESXi Hosts",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "192.168.13.135, 192.168.13.99, 192.168.13.194"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# <p align=\"center\"><strong>Watchtower Infrastructural Sensor Engine (WISE)</strong></p>\n<p align=\"center\">135 -> Host 13.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   194 -> Host 13.5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    99 -> Host 13.6</p>\n\n"
   }
  },
  {
   "title": "ESXi Host RAM Status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"PROC.*\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host CPU Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"Processor.*\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host Power Supply Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"Processor.*\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host Smart Storage Battery Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"Battery.*\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host Approximate Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"PowerSupply.*\", sensor_class=\"power\"}*2 ",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host Fan Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"Fan.*\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host Inlet Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"ambient\", sensor_class=\"temperature\", sensor_index=\"cpqHeTemperatureCelsius.0.1\"}*1.8+32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host Exhaust Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"$instance\", sensor_descr=~\"ambient\", sensor_class=\"temperature\", sensor_index=\"cpqHeTemperatureCelsius.0.15\"}*1.8+32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  }
 ]
}