{
 "title": "Watchtower Looking Glass",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "options": {
    "content": "# <p align=\"center\"><strong>Watchtower Looking Glass<strong></p>\n<p align=\"center\"><em>For nothing is hidden that will not become evident...</em></p>\n\n"
   }
  },
  {
   "title": "Global Switching + Transmission Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(librenms_ifInBits_rate+librenms_ifOutBits_rate)/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic per Network Port",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by (ifName,instance) (librenms_ifInBits_rate+librenms_ifOutBits_rate)/10000000",
     "legendFormat": "Port: {{ifName}} | IP: {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic per Network Device",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by (instance) (librenms_ifInBits_rate+librenms_ifOutBits_rate)/10000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmission Errors per Second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 39 },
   "targets": [
    { "expr": "sum(librenms_ifInErrors_rate)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic by Core Switch",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Security Camera Switch Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holmen Security Camera Switch Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}