{
 "title": "Watchtower Independent Neural Engine",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# <p align=\"center\"><strong>Watchtower Independent Neural Engine (WINE)</strong></p>\n<p align=\"center\"><em>For nothing is hidden that will not become evident...</em></p>\n\n"
   }
  },
  {
   "title": "Total Network Traffic Sent - ArcadiaDC (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"ArcadiaDC\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"ArcadiaDC\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"ArcadiaDC\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic Sent - newpdc (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"newpdc\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"newpdc\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"newpdc\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Authentication Projections (±2%)",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "windows_ad_ldap_writes_total_prophet {value_type=\"yhat_upper\"} * 1.02",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_ad_ldap_writes_total_prophet {value_type=\"yhat_lower\"} * 0.98",
     "legendFormat": "__auto"
    },
    { "expr": "windows_ad_ldap_writes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Network Traffic Sent - Stakeout (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"Stakeout\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"Stakeout\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"Stakeout\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic Sent - StarEnergy (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"StarEnergy\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"StarEnergy\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"StarEnergy\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic Sent - ESRI (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"ESRI\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"ESRI\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"ESRI\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArcadiaDC Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.9:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.9:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"ArcadiaDC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "newpdc Windows Processes Projection (±4%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.10:9182\", value_type=\"yhat_upper\"}*1.04",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.10:9182\", value_type=\"yhat_lower\"}*0.96",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"newpdc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stakeout Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.11:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.11:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"Stakeout\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StarEnergy Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.68:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.68:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"StarEnergy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESRI Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.16:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.16:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"ESRI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.112:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.112:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"Veeam\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam Proxy 1 Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.171:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.171:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"VeeamProxy1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArcadiaDC Total CPU Work Done Projection (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_upper\", exported_job=\"ArcadiaDC\"})*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_lower\", exported_job=\"ArcadiaDC\"})*0.95",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total {job=\"ArcadiaDC\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "newpdc Total CPU Work Done Projection (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_upper\", exported_job=\"newpdc\"})*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_lower\", exported_job=\"newpdc\"})*0.95",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total {job=\"newpdc\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stakeout Total CPU Work Done Projection (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_upper\", exported_job=\"Stakeout\"})*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_lower\", exported_job=\"Stakeout\"})*0.95",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total {job=\"Stakeout\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESRI Total CPU Work Done Projection (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_upper\", exported_job=\"ESRI\"})*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_lower\", exported_job=\"ESRI\"})*0.95",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total {job=\"ESRI\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam Total CPU Work Done Projection (±20%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_upper\", exported_job=\"Veeam\"})*1.20",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_lower\", exported_job=\"Veeam\"})*0.80",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total {job=\"Veeam\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam Proxy 1 Total CPU Work Done Projection (±20%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_upper\", exported_job=\"VeeamProxy1\"})*1.20",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total_prophet {value_type=\"yhat_lower\", exported_job=\"VeeamProxy1\"})*0.80",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (windows_cpu_processor_utility_total {job=\"VeeamProxy1\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}