{
 "title": "Watchtower Meraki Monitoring System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "# <p align=\"center\"><strong>Watchtower Meraki Switch Monitoring System</strong></p>\n<p align=\"center\"><em>Percent changes are relative to an hour ago - 5 minute refresh time - Ports must be sending one kilobyte per second to be considered active </em></p>\n\n"
   }
  },
  {
   "title": "Switch Response Times Measured from Watchtower Switch",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (monitor_name) (avg_over_time(monitor_response_time{monitor_name=\"Arcadia Core Switch\"}[1m]))",
     "legendFormat": "{{monitor_name}}"
    },
    {
     "expr": "avg by (monitor_name) (avg_over_time(monitor_response_time{monitor_name=\"Arcadia Switch 2\"}[1m]))",
     "legendFormat": "{{monitor_name}}"
    },
    {
     "expr": "avg by (monitor_name) (avg_over_time(monitor_response_time{monitor_name=\"Arcadia Switch 3\"}[1m]))",
     "legendFormat": "{{monitor_name}}"
    },
    {
     "expr": "avg by (monitor_name) (avg_over_time(monitor_response_time{monitor_name=\"Arcadia Switch 4\"}[1m]))",
     "legendFormat": "{{monitor_name}}"
    },
    {
     "expr": "avg by (monitor_name) (avg_over_time(monitor_response_time{monitor_name=\"Arcadia Camera Switch\"}[1m]))",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Arcadia Core Switch Bandwidth Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Core Active Ports (54 total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ports" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(librenms_ifInOctets_rate{instance=\"192.168.0.210\"} > 1000)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Arcadia Switch 2 Bandwidth Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Switch 2 Active Ports (54 total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ports" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(librenms_ifInOctets_rate{instance=\"192.168.0.111\"} > 1000)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Total Ports in Use (Last 5 minutes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ports" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((librenms_ifInOctets_rate{instance=~\"192.168.0.210|192.168.0.110|192.168.0.111|192.168.0.65|192.168.0.175\"}) > 1000)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Arcadia Switch 3 Bandwidth Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Switch 3 Active Ports (54 total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ports" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(librenms_ifInOctets_rate{instance=\"192.168.0.65\"} > 1000)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Arcadia Total Switch Bandwidth Usage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(librenms_ifInBits_rate{instance=~\"192.168.0.210|192.168.0.110|192.168.0.111|192.168.0.65|192.168.0.175\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Switch 4 Bandwidth Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Switch 4 Active Ports (54 total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ports" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(librenms_ifInOctets_rate{instance=\"192.168.0.110\"} > 1000)",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Arcadia Camera Switch Bandwidth Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Camera Switch Active Ports (30 total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ports" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(librenms_ifInOctets_rate{instance=\"192.168.0.175\"} > 1000)",
     "legendFormat": "{{ifName}}"
    }
   ]
  }
 ]
}