{
 "title": "Global Overview Revised",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Global CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (job) (rate(windows_cpu_processor_utility_total[3m])/rate(windows_cpu_processor_rtc_total[3m]))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Alerts Firing:", "type": "alertlist", "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 } },
  {
   "title": "Average Disk Activity (Megabyte per second)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_writes_total{volume =~ \"C:|S:|F:\"}[5m])+rate(windows_logical_disk_reads_total{volume =~ \"C:|S:|F:\"}[5m])",
     "legendFormat": "{{job}} {{volume}}"
    }
   ]
  },
  {
   "title": "Network Usage by Server - No Veeam (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job) (rate(windows_net_bytes_sent_total[5m]) + rate(windows_net_bytes_received_total[5m]))*0.000008\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_free_bytes{volume =~ \"C:|F:\"})/(windows_logical_disk_size_bytes{volume =~ \"C:|F:\"})*100",
     "legendFormat": "{{job}} {{volume}}"
    }
   ]
  },
  {
   "title": "RAM Free (Gigabytes)",
   "type": "gauge",
   "description": "Amount of RAM available in Gigabytes",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes / 1000000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server Room Live Feed (Arcadia)",
   "type": "text",
   "gridPos": { "h": 21, "w": 17, "x": 0, "y": 28 },
   "options": {
    "content": "<html><body>\r\n<iframe id=\"embeddedFrame\" src=\"http://cam1.devops.wt.local:80\" width=\"1290\" height=\"730\"></iframe>\r\n</body></html>"
   }
  },
  {
   "title": "Access Point Utilization",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"} + librenms_ifOutBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Server Room Ambient Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(librenms_sensor{instance=\"192.168.69.2\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"temperature\", sensor_descr=\"Chassis-Temperature\", sensor_index=\"12001\", sensor_type=\"entity-sensor\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holmen Server Room Ambient Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(librenms_sensor{instance=\"192.168.2.122\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"temperature\", sensor_descr=\"Chassis-Temperature\", sensor_type=\"entity-sensor\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Room Live Feed (Arcadia)",
   "type": "text",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 49 },
   "options": {
    "content": "<html><body>\r\n<iframe id=\"embeddedFrame\" src=\"http://cam2.devops.wt.local/cgi-bin/mjpeg?resolution=640x480&quality=1&page=1722024402677&Language=0\" width=\"645\" height=\"485\"></iframe>\r\n</body></html>"
   }
  },
  {
   "title": "Watchtower Network Logs Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/so_short_term\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logstash_events\" and r[\"_field\"] == \"in\")\n  |> derivative(nonNegative: true, unit: 1s, columns: [\"_value\"], timeColumn: \"_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"host\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> top(n: 1)"
    }
   ]
  },
  {
   "title": "Wildcard SSL Certificate Expires In:",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_cert_days_remaining{monitor_name=\"NISC.riverlandenergy.com\",monitor_type=\"http\",monitor_url=\"https://nisc.riverlandenergy.com\",monitor_hostname=\"null\",monitor_port=\"null\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alma Server Room Ambient Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(librenms_sensor{instance=\"192.168.3.254\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"temperature\", sensor_descr=\"Chassis-Temperature\", sensor_index=\"12001\", sensor_type=\"entity-sensor\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Server Room Line Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_power_line_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Amount of Blinks Recorded (Arcadia)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Blinks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_daemon_transfer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Holmen Server Room Line Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{sensor_class=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Per Access Point (Megabit per second)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{instance!=\"192.168.0.116\", ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"} + librenms_ifOutBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Room Live Feed (Holmen)",
   "type": "text",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 64 },
   "options": {
    "content": "<html><body>\r\n<iframe id=\"embeddedFrame\" src=\"http://cam3.devops.wt.local/cgi-bin/mjpeg?resolution=640x480&quality=1&page=1722024402677&Language=0\" width=\"645\" height=\"485\"></iframe>\r\n</body></html>"
   }
  },
  {
   "title": "Active Directory Database Modifications Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 71 },
   "targets": [
    {
     "expr": "rate(windows_ad_database_operations_total[10m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round-trip latency to riverlandenergy.com (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 71 },
   "targets": [
    {
     "expr": "(probe_icmp_duration_seconds{phase=\"rtt\"}*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes Running",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 79 },
   "targets": [
    { "expr": "windows_os_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Directory LDAP Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "targets": [
    { "expr": "windows_ad_ldap_writes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LDAP Opened Connections per Minute",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "rate(windows_ad_ldap_opened_connections_total[5m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Directory Successful Synchronization Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "windows_ad_replication_sync_requests_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower RAM Usage (Gigabytes)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes/1000000000"
    }
   ]
  },
  {
   "title": "Watchtower Ingest Traffic by Task (Megabit per second)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "((rate(pve_network_receive_bytes[45s]))*8)/1000000"
    }
   ]
  },
  {
   "title": "Active ELK Stack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/local-lvm\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Historical ELK Stack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/WT-Cold\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Other Telemetry Backups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/VM-Synology\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Total Telemetry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pve_disk_usage_bytes)/1000000000000"
    }
   ]
  },
  {
   "title": "Active Directory Search Suboperations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 141 },
   "targets": [
    {
     "expr": "windows_ad_directory_search_suboperations_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approximate Watchtower Stack Total RAM Usage (Gigabytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "sum(pve_memory_usage_bytes)/2/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower Stack CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "(pve_cpu_usage_ratio*100)" }
   ]
  },
  {
   "title": "Most Recent Connection Locations and Metrics",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 155 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "destination.geo.location:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DNS Requests Per Second",
   "type": "timeseries",
   "description": "The amount of DNS requests sent to ArcadiaDC or newpdc (primary and secondary DNS servers) on the Riverland Network",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 164 },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(windows_dns_queries_total[3m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "DNS Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 173 },
   "targets": [
    {
     "expr": "windows_service_state{job=~\"ArcadiaDC|newpdc\", name=\"dns\", state=\"running\"}"
    }
   ]
  },
  {
   "title": "Top Blocked DNS Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 174 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "DHCP Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 177 },
   "targets": [
    {
     "expr": "windows_service_state{job=~\"ArcadiaDC|newpdc\", name=\"dhcpserver\", state=\"running\"}"
    }
   ]
  },
  {
   "title": "DNS Responses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 181 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_dns_responses_total[60m])"
    }
   ]
  },
  {
   "title": "Recent Suspicious DNS Queries",
   "type": "logs",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 181 },
   "targets": [
    {
     "metrics": [
      { "id": "3", "settings": { "limit": "250" }, "type": "logs" }
     ],
     "query": "(\"ET DNS\" OR \"ET INFO DNS Query for Suspicious\") AND destination.ip:192.168.0.6 AND NOT soc.fields.requestMethod:GET AND NOT event.action:\"Searching Elasticsearch\" AND data_stream.dataset:suricata AND NOT \"ET EXPLOIT MS-SQL SQL Injection closing string plus line comment\" AND NOT source.ip:192.168.0.6 AND NOT source.ip:192.168.0.9 AND NOT source.ip:192.168.0.10",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top DNS Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 185 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Pihole DNS Filter Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 190 },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 11, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Percent Blocked Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "New Connections over Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 196 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "zeek",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DNS Queries Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today" }
   ]
  },
  {
   "title": "DNS Queries Blocked Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today" }
   ]
  },
  {
   "title": "Domains Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "DNS Queries Today over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 205 },
   "targets": [
    { "expr": "pihole_ads_blocked_today" },
    { "expr": "pihole_queries_forwarded" },
    { "expr": "pihole_queries_cached" }
   ]
  },
  {
   "title": "Active Pihole Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 211 },
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  },
  {
   "title": "Recent RDP Connections",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 215 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:rdp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent FTP Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 222 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:ftp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent VPN Connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 233 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:radius",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 242 },
   "options": {
    "content": "# Watchtower Infrastructural Sensor Engine (WISE)"
   }
  },
  {
   "title": "ESXi Host 13.4 Temperatures",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"192.168.13.135\", sensor_class=\"temperature\", __name__=\"librenms_sensor\"} * 1.8 + 32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host 13.4 - Approximate Server Power Draw (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 256 },
   "targets": [
    {
     "expr": "{__name__=\"librenms_sensor\", instance=\"192.168.13.135\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"power\", sensor_descr=\"PowerSupply-\", sensor_type=\"hpe-ilo\"} *2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESXi Host 13.5 Temperatures",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"192.168.13.194\", sensor_class=\"temperature\", __name__=\"librenms_sensor\"} * 1.8 + 32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host 13.5 - Approximate Server Power Draw (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 277 },
   "targets": [
    {
     "expr": "{__name__=\"librenms_sensor\", instance=\"192.168.13.194\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"power\", sensor_descr=\"PowerSupply-\", sensor_type=\"hpe-ilo\"} *2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESXi Host 13.6 Temperatures",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"192.168.13.99\", sensor_class=\"temperature\", __name__=\"librenms_sensor\"} * 1.8 + 32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host 13.6 - Approximate Server Power Draw (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 298 },
   "targets": [
    {
     "expr": "{__name__=\"librenms_sensor\", instance=\"192.168.13.99\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"power\", sensor_descr=\"PowerSupply-\", sensor_type=\"hpe-ilo\"}*2",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}