{
 "title": "Watchtower Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 }, "options": { "content": "# Watchtower Orchestration\n\n" } },
  {
   "title": "Watchtower Cluster RAM Usage (Gigabytes)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 10, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes/1000000000",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Watchtower Packets Analyzed Per Second ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(librenms_ifInUcastPkts_rate{instance=~\"192.168.0.+\"}) + sum(librenms_ifOutUcastPkts_rate{instance=~\"192.168.0.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower Logs Created per Second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf/so_short_term\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logstash_events\" and r[\"_field\"] == \"in\")\n  |> derivative(nonNegative: true, unit: 1s, columns: [\"_value\"], timeColumn: \"_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"host\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> top(n: 1)"
    }
   ]
  },
  {
   "title": "Packets Analyzed per Second in Arcadia",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(librenms_ifInUcastPkts_rate{instance=~\"192.168.0.+\"}) + sum(librenms_ifOutUcastPkts_rate{instance=~\"192.168.0.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Packets Analyzed in Arcadia",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(librenms_INUCASTPKTS{instance=~\"192.168.0.+\"}) + sum(librenms_INBROADCASTPKTS{instance=~\"192.168.0.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower Cluster CPU Usage (100% per item)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "pve_cpu_usage_ratio*100", "legendFormat": "{{id}}" }
   ]
  }
 ]
}