{
 "title": "Global Overview Revised",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Global CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (job) (rate(windows_cpu_processor_utility_total[3m])/rate(windows_cpu_processor_rtc_total[3m]))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Alerts Firing:", "type": "alertlist", "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 } },
  {
   "title": "Average Disk Activity (Megabyte per second)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_writes_total{volume =~ \"C:|S:|F:\"}[5m])+rate(windows_logical_disk_reads_total{volume =~ \"C:|S:|F:\"}[5m])",
     "legendFormat": "{{job}} {{volume}}"
    }
   ]
  },
  {
   "title": "Network Usage by Server - No Veeam (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job) (rate(windows_net_bytes_sent_total[5m]) + rate(windows_net_bytes_received_total[5m]))*0.000008\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_free_bytes{volume =~ \"C:|F:\"})/(windows_logical_disk_size_bytes{volume =~ \"C:|F:\"})*100",
     "legendFormat": "{{job}} {{volume}}"
    }
   ]
  },
  {
   "title": "RAM Free (Gigabytes)",
   "type": "gauge",
   "description": "Amount of RAM available in Gigabytes",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes / 1000000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Traffic Per Access Point (Megabit per second)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"} + librenms_ifOutBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Access Point Utilization",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (librenms_ifInBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"} + librenms_ifOutBits_rate{ifAlias=~\".*apr.*\", job=\"librenms\", measurement=\"ports\"}))/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Server Room Ambient Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(librenms_sensor{instance=\"192.168.69.2\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"temperature\", sensor_descr=\"Chassis-Temperature\", sensor_index=\"12001\", sensor_type=\"entity-sensor\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alma Server Room Ambient Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(librenms_sensor{instance=\"192.168.3.254\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"temperature\", sensor_descr=\"Chassis-Temperature\", sensor_index=\"12001\", sensor_type=\"entity-sensor\"}) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arcadia Front Copier Pages Printed since Last Restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"librenms_sensor\", instance=\"192.168.0.98\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"count\", sensor_descr=\"Impressions-since-powered-on\", sensor_index=\"prtMarkerPowerOnCount\", sensor_type=\"jetdirect\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holmen MFP Pages Printed since Last Restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"librenms_sensor\", instance=\"192.168.2.120\", job=\"librenms\", measurement=\"sensor\", sensor_class=\"count\", sensor_descr=\"Impressions-since-powered-on\", sensor_index=\"prtMarkerPowerOnCount\", sensor_type=\"jetdirect\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Toner Cyan",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"librenms\", index=\"1\", instance=\"192.168.0.97\", measurement=\"toner\", __name__=\"librenms_toner\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Toner Magenta",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"librenms\", index=\"2\", instance=\"192.168.0.97\", measurement=\"toner\", __name__=\"librenms_toner\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Toner Yellow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"librenms\", index=\"3\", instance=\"192.168.0.97\", measurement=\"toner\", __name__=\"librenms_toner\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations Toner Black",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"librenms\", index=\"4\", instance=\"192.168.0.97\", measurement=\"toner\", __name__=\"librenms_toner\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Directory Database Modifications Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(windows_ad_database_operations_total[10m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round-trip latency to riverlandenergy.com (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "(probe_icmp_duration_seconds{phase=\"rtt\"}*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Directory LDAP Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    { "expr": "windows_ad_ldap_writes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processes Running",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 68 },
   "targets": [
    { "expr": "windows_os_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Directory Successful Synchronization Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 68 },
   "targets": [
    {
     "expr": "windows_ad_replication_sync_requests_success_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Opened Connections per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(windows_ad_ldap_opened_connections_total[5m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower RAM Usage (Gigabytes)",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes/1000000000"
    }
   ]
  },
  {
   "title": "Watchtower Ingest Traffic by Task (Megabit per second)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "((rate(pve_network_receive_bytes[45s]))*8)/1000000"
    }
   ]
  },
  {
   "title": "Active ELK Stack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/local-lvm\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Historical ELK Stack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/WT-Cold\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Other Telemetry Backups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=\"storage/adam/VM-Synology\"}/1000000000000"
    }
   ]
  },
  {
   "title": "Total Telemetry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pve_disk_usage_bytes)/1000000000000"
    }
   ]
  },
  {
   "title": "Active Directory Search Suboperations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 127 },
   "targets": [
    {
     "expr": "windows_ad_directory_search_suboperations_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approximate Watchtower Stack Total RAM Usage (Gigabytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "sum(pve_memory_usage_bytes)/2/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower Stack CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "(pve_cpu_usage_ratio*100)" }
   ]
  },
  {
   "title": "Most Recent Connection Locations and Metrics",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 141 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "destination.geo.location:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DNS Requests Per Second",
   "type": "timeseries",
   "description": "The amount of DNS requests sent to ArcadiaDC or newpdc (primary and secondary DNS servers) on the Riverland Network",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 150 },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(windows_dns_queries_total[3m]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "DNS Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 159 },
   "targets": [
    {
     "expr": "windows_service_state{job=~\"ArcadiaDC|newpdc\", name=\"dns\", state=\"running\"}"
    }
   ]
  },
  {
   "title": "Top Blocked DNS Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 160 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "DHCP Server Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 163 },
   "targets": [
    {
     "expr": "windows_service_state{job=~\"ArcadiaDC|newpdc\", name=\"dhcpserver\", state=\"running\"}"
    }
   ]
  },
  {
   "title": "DNS Responses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 167 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(windows_dns_responses_total[60m])"
    }
   ]
  },
  {
   "title": "Recent Suspicious DNS Queries",
   "type": "logs",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 167 },
   "targets": [
    {
     "metrics": [
      { "id": "3", "settings": { "limit": "250" }, "type": "logs" }
     ],
     "query": "(\"ET DNS\" OR \"ET INFO DNS Query for Suspicious\") AND destination.ip:192.168.0.6 AND NOT soc.fields.requestMethod:GET AND NOT event.action:\"Searching Elasticsearch\" AND data_stream.dataset:suricata AND NOT \"ET EXPLOIT MS-SQL SQL Injection closing string plus line comment\" AND NOT source.ip:192.168.0.6 AND NOT source.ip:192.168.0.9 AND NOT source.ip:192.168.0.10",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top DNS Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 171 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Pihole DNS Filter Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 176 },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 11, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Percent Blocked Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "New Connections over Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 182 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "zeek",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DNS Queries Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today" }
   ]
  },
  {
   "title": "DNS Queries Blocked Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today" }
   ]
  },
  {
   "title": "Domains Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "DNS Queries Today over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 191 },
   "targets": [
    { "expr": "pihole_ads_blocked_today" },
    { "expr": "pihole_queries_forwarded" },
    { "expr": "pihole_queries_cached" }
   ]
  },
  {
   "title": "Active Pihole Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 197 },
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  },
  {
   "title": "Recent RDP Connections",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 201 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:rdp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent FTP Connections",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 208 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:ftp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent VPN Connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 219 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "tags:radius",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 228 },
   "options": {
    "content": "# Watchtower Infrastructural Sensor Engine (WISE)"
   }
  },
  {
   "title": "ESXi Host 13.4 Temperatures",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"192.168.13.135\", sensor_class=\"temperature\", __name__=\"librenms_sensor\"} * 1.8 + 32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host 13.5 Temperatures",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"192.168.13.194\", sensor_class=\"temperature\", __name__=\"librenms_sensor\"} * 1.8 + 32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "ESXi Host 13.6 Temperatures",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"192.168.13.99\", sensor_class=\"temperature\", __name__=\"librenms_sensor\"} * 1.8 + 32",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  }
 ]
}