{
 "title": "Watchtower Independent Neural Engine",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# <p align=\"center\"><strong>Watchtower Independent Neural Engine (WINE)</strong></p>\n<p align=\"center\"><em>For nothing is hidden that will not become evident...</em></p>\n\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 }, "options": { "content": "# Network Traffic Projections" } },
  {
   "title": "Total Network Traffic Sent - ArcadiaDC (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"ArcadiaDC\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"ArcadiaDC\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"ArcadiaDC\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic Sent - newpdc (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 2 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"newpdc\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"newpdc\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"newpdc\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Authentication Projections (±2%)",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "windows_ad_ldap_writes_total_prophet {value_type=\"yhat_upper\"} * 1.02",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_ad_ldap_writes_total_prophet {value_type=\"yhat_lower\"} * 0.98",
     "legendFormat": "__auto"
    },
    { "expr": "windows_ad_ldap_writes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Network Traffic Sent - Stakeout (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"Stakeout\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"Stakeout\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"Stakeout\", nic=\"Intel_R__PRO_1000_MT_Network_Connection\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic Sent - StarEnergy (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"StarEnergy\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"StarEnergy\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"StarEnergy\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 25 },
   "options": {
    "content": "# Windows Process Quantity Projections"
   }
  },
  {
   "title": "Total Network Traffic Sent - ESRI (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_upper\", exported_job=\"ESRI\"}/1000000000)*1.05",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total {job=\"ESRI\"}/1000000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(windows_net_bytes_sent_total_prophet {value_type=\"yhat_lower\", exported_job=\"ESRI\"}/1000000000)*0.95",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArcadiaDC Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.9:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.9:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"ArcadiaDC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "newpdc Windows Processes Projection (±4%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.10:9182\", value_type=\"yhat_upper\"}*1.04",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.10:9182\", value_type=\"yhat_lower\"}*0.96",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"newpdc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESRI Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.16:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.16:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"ESRI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stakeout Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.11:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.11:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"Stakeout\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StarEnergy Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.68:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.0.68:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"StarEnergy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam Windows Processes Projection (±8%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.13.12:9182\", value_type=\"yhat_upper\"}*1.08",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes_prophet {exported_instance=\"192.168.13.12:9182\", value_type=\"yhat_lower\"}*0.92",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes {job=\"Veeam\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "# Available System RAM Projections"
   }
  },
  {
   "title": "ArcadiaDC - Projected Free System RAM (Gigabytes) (±10%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"ArcadiaDC\", value_type=\"yhat_upper\"}/1000000000*1.10",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"ArcadiaDC\", value_type=\"yhat_lower\"}/1000000000*0.90",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes {job=\"ArcadiaDC\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "newpdc - Projected Free System RAM (Gigabytes) (±10%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"newpdc\", value_type=\"yhat_upper\"}/1000000000*1.10",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"newpdc\", value_type=\"yhat_lower\"}/1000000000*0.9",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes {job=\"newpdc\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stakeout - Projected Free System RAM (Gigabytes) (±10%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"Stakeout\", value_type=\"yhat_upper\"}/1000000000*1.10",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"Stakeout\", value_type=\"yhat_lower\"}/1000000000*0.90",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes {job=\"Stakeout\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ESRI - Projected Free System RAM (Gigabytes) (±10%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"ESRI\", value_type=\"yhat_upper\"}/1000000000*1.10",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"ESRI\", value_type=\"yhat_lower\"}/1000000000*0.90",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes {job=\"ESRI\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam - Projected Free System RAM (Gigabytes) (±10%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"Veeam\", value_type=\"yhat_upper\"}/1000000000*1.10",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"Veeam\", value_type=\"yhat_lower\"}/1000000000*0.90",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes {job=\"Veeam\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veeam Proxy 1 - Projected Free System RAM (Gigabytes) (±5%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"VeeamProxy1\", value_type=\"yhat_upper\"}/1000000000*1.10",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes_prophet {exported_job=\"VeeamProxy1\", value_type=\"yhat_lower\"}/1000000000*0.90",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes {job=\"VeeamProxy1\"}/1000000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}