{
 "title": "Watchtower Synology Monitoring System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# <p align=\"center\"><strong>Watchtower Alma Synology Monitoring System</strong></p>\n<p align=\"center\"><em>Zachary Pax 2024 for Riverland Energy Cooperative</em></p>\n\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_type=\"diskHealthStatusState\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_used{instance=\"192.168.3.186\", mempool_class=\"system\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "librenms_free{instance=\"192.168.3.186\", mempool_class=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_type=\"diskStatusState\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "librenms_1min{instance=\"192.168.3.186\", measurement=\"ucd_load\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synology Temperature Sensors",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_class=\"temperature\"}+32*1.8",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_type=\"raidStatusState\"}",
     "legendFormat": "{{sensor_descr}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_type=\"cpuFanStatusState\"}",
     "legendFormat": "{{sensor_descr}}"
    },
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_type=\"systemFanStatusState\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "librenms_sensor{instance=\"192.168.3.186\", sensor_type=\"powerStatusState\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchtower Scraping Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librenms_poller{instance=\"192.168.3.186\", module=\"ALL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency from Arcadia",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=\"Alma Synology\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}