from(bucket: "data")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "veeam_vbr_sessions")
  |> filter(fn: (r) => r["_field"] == "veeamVBRSessionsJobResult")
  |> filter(fn: (r) => r["veeamVBRSessionJobName"] == "REDACTED")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
