from(bucket: "data")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_field"] == "restorePointsCount")
  |> filter(fn: (r) => r["_field"] == "veeamVBRMSInternalID" or r["_field"] == "restorePointsCount")
  |> filter(fn: (r) => r["veeamVBR"] == "192.168.13.12")
  |> filter(fn: (r) => r["_measurement"] == "veeam_vbr_backupobjects")
  |> filter(fn: (r) => r["veeamVBRBobjectName"] == "REDACTED")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")
