from(bucket: "data")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "veeam_vbr_sessions")
  |> filter(fn: (r) => r["_field"] == "veeamBackupSessionsTimeDuration")
  |> filter(fn: (r) => r["veeamVBR"] == "192.168.13.12")
  |> filter(fn: (r) => r["veeamVBRSessionJobName"] == "REDACTED")
  |> filter(fn: (r) => r["veeamVBRSessionsJobResultMessage"] == "Success")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
